### ISSUE TITLE
it says structures can generate in biomes they cannot

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#321] opened 2024-09-26 09:20 UTC
![image](https://github.com/user-attachments/assets/5244e982-5cc1-4a94-bf23-3cf382c53758)
![2024-09-26_11 19 33](https://github.com/user-attachments/assets/d16d48a6-ca73-424c-8ae9-3836ba5dc64b)

**Comment by ghost** [comment] 2024-09-26 09:20
igloos cannot generate in jagged peaks

**Comment by Cubitect** [comment] 2024-10-07 21:04
The tool-tip in the corner shows the biome at the location of your mouse. As your mouse pointer is not visible in the screenshot I suspect that the biome is different at the igloo position.

I'll close this, since there is no information here at all on how to reproduce the problem.
If this indeed a problem that you can reproduce, then you need to provide at a minimum, the affected seed and game version.

**Closed as completed by Cubitect** 2024-10-07 21:04 UTC
