### ISSUE TITLE
"approximate" surface height is very generous

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#319] opened 2024-09-23 15:33 UTC
![2024-09-23_17 30 43](https://github.com/user-attachments/assets/640ce1b3-b9ca-4876-aeb2-0fc8495250ae)
![image](https://github.com/user-attachments/assets/324cd664-76b2-4600-a237-f1a0505c78dc)

**Comment by Cubitect** [comment] 2024-10-07 21:48
In general, please provide steps to reproduce an issue, such as a seed, location, game version, etc. Also make sure you are using a vanilla version of the game, when comparing the world generation (I mention this because of your other issue #327).

All the climate maps are gray-scale, so I can only guess that lower screenshot is supposed to be the surface height for the in-game terrain above?

The approximate surface height is based on the climate and biomes, which is not a perfect bases by any means and the biggest discrepancies are usually due to cave entrances and aquifers. Your example, could also be from a river biome that happened to be badly represented by the terrain (though it seems unusually large for that).

I'll close this issue for now, since there is not enough information here.

**Closed as completed by Cubitect** 2024-10-07 21:48 UTC
