### ISSUE TITLE
Feature request: The ability to see biome layers in map

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#109] opened 2022-03-06 02:17 UTC
Similar to the minemap feature, like this, easy to see hills, biomes, being filtered.

![image](https://user-images.githubusercontent.com/23464599/156906338-26198cda-808e-4d0e-923e-b4f6395b5ba4.png)

![image](https://user-images.githubusercontent.com/23464599/156906352-f6656e92-f995-4429-9969-93d965ce9638.png)

**Comment by Cubitect** [comment] 2022-05-24 19:22
Duplicate of #97.
The different scales of the biome search filters are now available options in the map view in v2.2.0.
It's not all the layers, but it covers arguably the most interesting of the 'layers' by abstracting away much of the messy layer hierarchy that changes a fair bit between versions.

**Closed as completed by Cubitect** 2022-05-24 19:22 UTC
