### ISSUE TITLE
Feature request: Export biome map to image

### ISSUE THREAD

**Issue by FakenameBill** [Cubitect/cubiomes-viewer#96] opened 2022-01-02 14:59 UTC
The feature I am requesting works exactly the same as AMIDST's "export biomes to image" feature.
The user inputs sets of X and Z coordinates bounding a rectangular region of the world, and the program saves a PNG image of the biome map of the region at full resolution (1 pixel for every 2x2 blocks).

This feature would allow for the creation of precise biome maps of very specific regions of the world, useful for comparison across different versions. While AMIDST can do this for versions before 1.18, AMIDST appears to be abandoned, and currently the only way to make a high-resolution map of a block-specific region of 1.18 biomes is to use the Cubiomes C library, which users without programming experience may find difficult.

**Comment by Cubitect** [comment] 2022-05-24 19:40
This is pretty much possible now with the biome image export in v2.2.0, although not for the scale you are describing. One pixel for 2x2 blocks also seems weird to me, since the in-game biome generation is scale 1:4 with a voronoi interpolation for the block level. 
(Also mostly a duplicate of #59)

**Closed as completed by Cubitect** 2022-05-24 19:40 UTC
