### ISSUE TITLE
False malware detection by Bkav Pro: W32.AIDetectMalware.64

### ISSUE THREAD

**Issue by 1GodRage** [Cubitect/cubiomes-viewer#262] opened 2023-10-08 20:04 UTC
**Problem:** Malware detected.

https://www.virustotal.com/gui/file/cd1ca7e9a9f985afb1f8dfea9dad106bb4b18eb991e253c9993249035dfad10b/detection
**cubiomes-viewer-3.3.0-w64.exe**
Bkav Pro: W32.AIDetectMalware.64

**Solution:** in case of false positive, send the zip to https://www.bkav.com/contact-us

**Comment by 69b69t** [comment] 2023-10-08 20:17
compile from source and check that file. probably virustotal being weird

**Comment by 1GodRage** [comment] 2023-10-10 17:13
Compiling skill is out of my domain. _(And I've heard that some compilers are the source of Trojans...)_
But scanning any file before downloading is in my domain.
Virustotal being weird? What do you mean?

**Comment by Cubitect** [comment] 2023-10-11 20:50
This is curious since all the releases up to 3.2.1 are fine.

I have not changed my build setup at all for the releases, so Bkav Pro must take issue with some of the changes between 3.2.1 and 3.3.0. My best guess is that its caused by the bundled translation files that were added for the internationalization. When I get some time, I'll try confirm this or identify the change that caused it.

In case anyone is really worried and wants to replicate the binary:
I'm using a virtual machine of Windows 10 Home (20H2) that's dedicated for these releases, with a static build of Qt.
To compile Qt I followed the, by now outdated, [instructions on the wiki](https://wiki.qt.io/Building_a_static_Qt_for_Windows_using_MinGW), with:

* MinGW 8.1.0 from its [sourceforge page](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/)
* Qt 5.15.3 sources, cloned from git://code.qt.io/qt/qt5.git

My Qt build options were:
```
$ perl init-repository --module-subset=default,-qtwebengine
$ configure -static -opensource -confirm-license -opengl -recheck-all -nomake tests -nomake examples -skip qtwebengine
```

**Comment by Cubitect** [comment] 2023-10-14 11:02
After some experimentation I've determined that the false positive is triggered by the biome lookup table in the cubiomes library.

My initial assessment suspecting the changes between 3.2.1 and 3.3.0 was based on VirusTotal not reporting issues wíth release 3.2.1. However, it appears that W64.AIDetectMalware was added to the list of scanners relatively recently and the result of a previous scan was cached. The "Reanalyze" feature on the website also does not work as expected.

Since this is not directly an issue with Cubiomes-Viewer but with the cubiomes library (or rather with the virus scanners), I'll close this issue in favor of https://github.com/Cubitect/cubiomes/issues/110.

**Comment by Cubitect** [comment] 2023-12-09 11:31
I have tried some test builds without the biome lookup table and with large parts of the program removed, and the false malware detection by Bkav Pro persists. I now suspect that the very use of Qt triggers the issue. In any case, the cubiomes library may not be sole problem after all, so I'll reopen this issue of now.

I have reported the false detection to Bkav.

**Comment by Cubitect** [comment] 2024-02-10 20:13
I have not got a reply from Bkav, but the issue seems to be resolved. At least version 4.0 is no longer is flagged on VirusTotal:
https://www.virustotal.com/gui/file/aa48b4d461136a2a9af9dc2441ab1b3bd44dde3fbfc1ef4c041bc8ff5ba9a07a

**Closed as completed by Cubitect** 2024-02-10 20:13 UTC
