### ISSUE TITLE
Suggestion on adding set list of seeds into Cubiomes, and then search trough those seeds you selected.

### ISSUE THREAD

**Issue by Killstepz** [Cubitect/cubiomes-viewer#12] opened 2021-01-30 12:00 UTC
basically its simple, it would just work like Sassa's tool where you can select 'Set Seeds with the option of putting int a .txt file with a list of seeds, best example: a list of sisterseeds wich shares the same nether across all seeds, so you would put in all your 655536 sister seeds into a .txt file then upload the file to cubiomes and then use cubiomes to search all those sister seeds for a overworld you like, this way it would be much easier to search for seeds wich share the same nether dimension using Seedcandy to get your sister seeds and cubiomes to search for the seeds you like, instead of going into seedcandy and, get the 1 reduce to strucutre seed to get its hex code for cubiomes. and also maybe even add an option into cubiomes to get the sisterseeds there instead of seedcandy this would even be better. its just an idea :)

**Comment by bogdan-barbu** [comment] 2021-01-30 15:48
Maybe take a bit to structure your text because that whole paragraph is essentially one messy sentence. As far as I understand, your request is to search a predefined list of seeds.

**Comment by Delvin4519** [comment] 2021-01-30 16:57
Duplicate of https://github.com/Cubitect/cubiomes-viewer/issues/3 where I already requested a feature to import a text list of seeds to scan

**Comment by Killstepz** [comment] 2021-01-30 23:40
> Duplicate of #3 where I already requested a feature to import a text list of seeds to scan

I didint notice, my bad, ahh well we both suggested it now in different ways i gues :p

**Comment by Cubitect** [comment] 2021-02-24 17:33
I rewrote most of the search algorithm for v1.3, and it now supports loading custom seed lists. However, from what I understand, you want to provide a seed list for the lower 48-bit and search through the family that consists of all the top 16-bit values. I might add this at some point as I've been looking at finding seed bases for multiple quad-huts again recently, which is a little more involved and I don't think there will be support in the GUI tool. Loading a custom list for the 48-bit seeds might be an acceptable alternative.

**Comment by Cubitect** [comment] 2021-06-04 00:30
Custom 48-bit seed lists are now also possible in v1.6.0.

**Closed as completed by Cubitect** 2021-06-04 00:30 UTC
