### ISSUE TITLE
Strongholds not being detected in a close radius

### ISSUE THREAD

**Issue by masterwyatt** [Cubitect/cubiomes-viewer#105] opened 2022-02-13 06:32 UTC
When searching for a stronghold near spawn after a certain radius it doesn't detect anything anymore. Which doesn't seem right because in this seed it seems to have a stronghold much closer than 800 blocks from spawn. If I decrease the stronghold radius by 1 it doesn't find the seed anymore. I don't know if I'm wrong or the program is having an issue.
![Untitled](https://user-images.githubusercontent.com/66440657/153741684-d69e607b-12d1-4b13-a7af-46ac61d39f9b.png)
.

![image](https://user-images.githubusercontent.com/66440657/153741740-b8eb8121-ad01-4bf9-9d24-667bc27c1906.png)

**Comment by Cubitect** [comment] 2022-02-15 21:44
There are a couple of issues with the stronghold filter which have been addressed in version [2.0.dev2](https://github.com/Cubitect/cubiomes-viewer/releases/tag/2.0.dev2).
However, I'm not sure if that is your problem, since I was unable to reproduce this, but I don't see anything wrong in the screenshot.
Does this problem persist in the newest pre-release?

**Comment by masterwyatt** [comment] 2022-02-17 02:50
Seems to be fixed thank you!

**Closed as completed** 2022-03-02 23:05 UTC
