### ISSUE TITLE
Seed list gives different results sometimes with stronghold distance

### ISSUE THREAD

**Issue by masterwyatt** [Cubitect/cubiomes-viewer#176] opened 2022-11-14 22:48 UTC
Basically seed searching for stronghold distance from the spawn i set the centred square side to 1300 and sometimes from the seedlist it pops up 3 seeds for example and then run it again its 2 seeds. Also some seeds have a stronghold thats farther then the distance I set it. Hopefully this is not too vague.

**Comment by masterwyatt** [comment] 2022-11-15 13:06
Also to clarify I was searching with this on version 1.18

**Comment by Cubitect** [comment] 2022-11-15 22:30
I am not entirely sure I understand. Do you actually get incorrect results, or are you just concerned that the seeds that are found can be different between runs?

A discrepancy can arise for searches that produce seeds very quickly, while also using the "Stop on results" option.

"Stop on results" simply stops the search once any results are found, but since the trial seeds are distributed among the search threads, you will just get the results from the thread that was the fastest. There is not much to be done against this, except limit the search to a single thread.

However, the latest update also introduced a limit on the number of UI updates, and seeds will be buffered for a short time so even with a single thread you can get a different number of results, but the seed values should remain the same.

**Comment by masterwyatt** [comment] 2022-11-16 12:39
I was trying to say that both of those things happen. The seed sometimes doesn’t show up, and that the stronghold dist from spawn is completely inaccurate most of the time, if you need a seed for an example I can give you one

**Comment by Cubitect** [comment] 2022-11-16 13:01
Yes, I need to know the exact conditions, examples of incorrect seeds, your OS and the tool version, if it isn't the latest.
Ideally, just export your session (File > Save session) and attach it here.

**Comment by Cubitect** [comment] 2023-01-19 23:10
Closing by assumption this is a non-issue caused by the non-immediate stop.

**Closed as completed by Cubitect** 2023-01-19 23:10 UTC
