### ISSUE TITLE
False positive for woodland mansion in V1.19

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#155] opened 2022-08-28 02:01 UTC
Cubiomes says there is a mansion at 0,0 on -1034420513776306998 on 1.19 but there is no mansion in-game

**Comment by mooing-cowmilk** [comment] 2022-08-28 02:43
-128071063668497579 is another seed

**Comment by Cubitect** [comment] 2022-09-11 12:49
A recent change I made in v2.3.2 that was meant to improve accuracy was implemented incorrectly and essentially made all Mansions incorrect. This should be fixed in v2.4.0.

**Comment by Cubitect** [comment] 2022-09-11 13:01
Some related things that I want to point out, although they probably aren't the cause for this issue:

Desert Pyramids, Jungle Temples, as well as Woodland Mansions to a lesser extent, depend on the actual surface height in 1.18+, which cubiomes currently cannot determine. Instead it uses the climate parameters and biomes to estimate the surface height, but that is not always sufficient.

There is now an advanced option to disable terrain checks, which will avoid false negatives at the cost of significantly more false
positives.

**Closed as completed** 2022-09-11 22:52 UTC
